# Network interface settings
interface: "en0"
snapshot_length: 1600
promisc_mode: true
timeout: "0s"  # Use "0s" for infinite, or specify duration like "30s", "5m"
filter: "tcp"
verbose: false

# Color scheme configuration
color_scheme:
  Authentication: "red,bold"
  API Key: "red,bold"
  Credit Card: "red,bold"
  Private Key: "red,bold"
  JWT: "red,bold"
  Email: "yellow,bold"
  Sensitive Protocol: "magenta,bold"
  Known Application: "blue,bold"
  TLS SNI: "cyan,bold"
  Interesting Path: "green,bold"
  Default: "gray,bold"
  Social Security Number: "red,bold"
  Bank Account: "yellow,bold"
  IP Address: "cyan,bold"
  Session ID: "magenta,bold"
  License Key: "green,bold"
  Shipping Address: "blue,bold"
  Phone Number: "yellow,bold"
  Tax Identification Number: "magenta,bold"
  Health Information: "red,bold"
  Subscription: "green,bold"
  Password Reset: "yellow,bold"
  Login: "red,bold"
  Orders: "blue,bold"
  Reports: "cyan,bold"
  Notifications: "green,bold"
  Files: "magenta,bold"
  Logs: "yellow,bold"
  Slack: "blue,bold"
  MySQL: "blue,bold"
  MongoDB: "green,bold"
  Redis: "yellow,bold"
  API: "green,bold"
  HTTP: "cyan,bold"
  FTP: "magenta,bold"
  IMAP: "red,bold"
  SMTP: "blue,bold"

# Well-known ports
well_known_ports:
  80: "HTTP"
  443: "HTTPS"
  21: "FTP"
  22: "SSH"
  23: "Telnet"
  25: "SMTP"
  53: "DNS"
  110: "POP3"
  143: "IMAP"
  3306: "MySQL"
  5432: "PostgreSQL"
  27017: "MongoDB"
  8080: "HTTP (Alternate)"
  8443: "HTTPS (Alternate)"
  3389: "RDP"
  5900: "VNC"
  6379: "Redis"
  11211: "Memcached"
  162: "SNMP Trap"
  514: "Syslog"
  1433: "MS SQL Server"
  1521: "Oracle DB"
  1434: "MS SQL Server (UDP)"
  25565: "Minecraft"
  4567: "OpenVPN"
  5000: "UPnP"

applications:
  Netflix:
    - "netflix.com"
    - "nflx.net"
    - "nflxext.com"
    - "nflximg.com"
    - "nflximg.net"
    - "nflxso.net"
    - "nflxvideo.net"
  YouTube:
    - "youtube.com"
    - "googlevideo.com"
    - "ytimg.com"
    - "yt.be"
    - "youtu.be"
    - "youtube-nocookie.com"
  Facebook:
    - "facebook.com"
    - "fbcdn.net"
    - "facebook.net"
    - "fb.com"
    - "fb.me"
    - "messenger.com"
  Instagram:
    - "instagram.com"
    - "cdninstagram.com"
    - "ig.me"
  Twitter:
    - "twitter.com"
    - "twimg.com"
    - "t.co"
    - "x.com"
  TikTok:
    - "tiktok.com"
    - "musical.ly"
    - "bytedance.com"
    - "tiktokcdn.com"
    - "tiktokv.com"
  Snapchat:
    - "snapchat.com"
    - "snap.com"
    - "snapkit.com"
  LinkedIn:
    - "linkedin.com"
    - "licdn.com"
    - "linkedin.net"
  WhatsApp:
    - "whatsapp.com"
    - "whatsapp.net"
    - "web.whatsapp.com"
  Zoom:
    - "zoom.us"
    - "zoom.com"
    - "zoomgov.com"
  Spotify:
    - "spotify.com"
    - "spotify.net"
    - "spotifycdn.com"
    - "spotifycharts.com"
    - "scdn.co"
  Bolt:
    - "bolt.eu"
    - "bolt.com"
    - "bolt.eu.com"
    - "boltapp.eu"
  Google Drive:
    - "drive.google.com"
    - "docs.google.com"
    - "sheets.google.com"
    - "slides.google.com"
  Dropbox:
    - "dropbox.com"
    - "dropboxusercontent.com"
    - "dropboxstatic.com"
    - "dropboxapi.com"
  Microsoft OneDrive:
    - "onedrive.live.com"
    - "onedrive.com"
    - "1drv.ms"
    - "sharepoint.com"
  Skype:
    - "skype.com"
    - "skype.net"
    - "skypeassets.com"
  Pinterest:
    - "pinterest.com"
    - "pinimg.com"
    - "pin.it"
  Discord:
    - "discord.com"
    - "discordapp.com"
    - "discord.gg"
    - "discord.media"
  Slack:
    - "slack.com"
    - "slack-imgs.com"
    - "slack-edge.com"
    - "slack.global"
  GitHub:
    - "github.com"
    - "githubusercontent.com"
    - "githubapp.com"
    - "githubassets.com"
    - "git.io"
  Reddit:
    - "reddit.com"
    - "redd.it"
    - "redditstatic.com"
    - "redditmedia.com"
  Twitch:
    - "twitch.tv"
    - "ttvnw.net"
    - "jtvnw.net"
    - "twitchcdn.net"
  Adobe:
    - "adobe.com"
    - "acrobat.com"
    - "adobelogin.com"
    - "adobecc.com"
    - "typekit.net"
    - "adobedtm.com"
  ZoomInfo:
    - "zoominfo.com"
    - "zoominfo.net"
    - "zoominfo-api.com"
  Yelp:
    - "yelp.com"
    - "yelpcdn.com"
    - "yelpreservations.com"
    - "yelpstatic.com"
  eBay:
    - "ebay.com"
    - "ebayimg.com"
    - "ebaystatic.com"
    - "ebayinc.com"
    - "ebaydesc.com"
  Amazon:
    - "amazon.com"
    - "amazon.co.uk"
    - "amazonaws.com"
    - "amzn.com"
    - "amzn.to"
    - "amazon-adsystem.com"
  Apple:
    - "apple.com"
    - "icloud.com"
    - "cdn-apple.com"
    - "mzstatic.com"
    - "apple-cloudkit.com"
    - "apple.news"
    - "apple.maps"
  Apple Music:
    - "music.apple.com"
    - "itunes.apple.com"
    - "music.apple.com"
  iCloud:
    - "icloud.com"
    - "icloud-content.com"
    - "icloud.apple.com"
    - "www.icloud.com"
  App Store:
    - "apps.apple.com"
    - "itunes.apple.com"
    - "appstore.com"
  Apple TV:
    - "tv.apple.com"
    - "play.itunes.apple.com"
  iMessage:
    - "imessage.apple.com"
    - "messages.apple.com"
  FaceTime:
    - "facetime.apple.com"
    - "faceTime.apple.com"
  Apple Arcade:
    - "arcade.apple.com"
  Apple Fitness:
    - "fitness.apple.com"
  Apple Books:
    - "books.apple.com"
  Apple News:
    - "news.apple.com"
    - "apple.news"
  Apple Maps:
    - "maps.apple.com"
    - "apple.maps"
  Apple Developer:
    - "developer.apple.com"
    - "devimages-cdn.apple.com"
    - "swift.org"


# Interesting paths patterns
interesting_paths:
  Login: "(?i)/login|/auth|/signin|/oauth"
  Admin: "(?i)/admin|/console|/dashboard"
  API: "(?i)/api/|/v1/|/v2/|/graphql"
  Payment: "(?i)/payment|/checkout|/cart"
  User Data: "(?i)/user|/account|/profile"
  File Transfer: "(?i)/upload|/download|/file|/document"
  Search: "(?i)/search|/find|/query"
  Registration: "(?i)/register|/signup|/create-account"
  Logout: "(?i)/logout|/signout"
  Orders: "(?i)/order|/history|/transactions"
  Settings: "(?i)/settings|/preferences|/config"
  Notifications: "(?i)/notifications|/alerts|/messages"
  Payment History: "(?i)/payment-history|/invoice|/receipt"
  Subscription: "(?i)/subscribe|/plan|/subscription"
  Contact Us: "(?i)/contact|/support|/help"
  Verification: "(?i)/verify|/confirm|/activation"
  Password Reset: "(?i)/reset-password|/forgot-password"
  Reports: "(?i)/report|/analytics|/statistics"
  Logs: "(?i)/logs|/error|/debug"
  Files: "(?i)/files|/documents|/assets"

# Sensitive data patterns
sensitive_patterns:
  Email: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
  Credit Card: "\\b(?:\\d[ -]*?){13,16}\\b"
  Authentication: "(?i)login|credential|password|token|key|secret|bearer"
  API Key: "(?i)(api[_-]?key|access[_-]?key|secret[_-]?key).[a-zA-Z0-9]{16,}"
  JWT: "eyJ[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*"
  Private Key: "(?i)-----BEGIN.*PRIVATE KEY-----"
  Social Security Number: "\\b(?:\\d{3}-?\\d{2}-?\\d{4}|\\d{3} ?\\d{2} ?\\d{4})\\b"
  Bank Account: "(?i)account[_-]?number|iban|sort[_-]?code|bank[_-]?account"
  IP Address: "(?i)\\b(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b"
  Date of Birth: "(?i)dob|birthdate|birth[_-]?date|birthday"
  Session ID: "(?i)session[_-]?id|sid|session[_-]?token"
  Encryption Key: "(?i)-----BEGIN.*ENCRYPTION KEY-----"
  Access Token: "(?i)access[_-]?token|oauth[_-]?token"
  Master Key: "(?i)master[_-]?key|primary[_-]?key"
  PIN: "(?i)pin[_-]?code|pin[_-]?number"
  License Key: "(?i)license[_-]?key|product[_-]?key"
  Shipping Address: "(?i)address|shipping[_-]?address|delivery[_-]?address"
  Phone Number: "\\b\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}\\b"
  Tax Identification Number: "(?i)tin|tax[_-]?id|taxpayer[_-]?id"
  Credit Score: "(?i)credit[_-]?score|fico[_-]?score"
  Health Information: "(?i)health[_-]?data|medical[_-]?records|patient[_-]?info"

# Protocol patterns
protocol_patterns:
  HTTP: "^(?:GET|POST|HEAD|PUT|DELETE|OPTIONS|CONNECT|TRACE)\\s"
  TLS: "^\x16\x03[\x00-\x03]"
  SSH: "^SSH-\\d\\.\\d"
  SMTP: "^(?:220|250|354|450|500)"
  FTP: "^(?:220|230|331|530)"
  DNS: "^.{2}[\x01\x02].{2}"
  BitTorrent: "^(\x13|d1:)BitTorrent protocol"
  IMAP: "^\\*\\s+OK\\s+IMAP4\\s+rev[0-9]+\\s+server\\s+ready"
  Telnet: "^\\xFF\\xFD"
  RDP: "^\\x03\\x00\\x00\\x13"
  SNMP: "^\\x30\\x2c"
  HTTP2: "^\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00"
  LDAP: "^(?:BIND|SEARCH|MODIFY|ADD|DELETE|COMPARE|ABANDON)"
  MQTT: "^\\x10|\\x20|\\x30|\\x40|\\x50"
  SIP: "^(?:INVITE|ACK|BYE|CANCEL|OPTIONS|REGISTER|UPDATE)"
  SMB: "^\\x00\\x00\\x00\\x85\\x00\\x00\\x00\\x00"
  XMPP: "^<\\?xml version=\"1.0\" encoding=\"UTF-8\"\\?>"
  DHCP: "^\\x01\\x01\\x06"
  Redis: "^\\*\\d+\\r\\n"
  MySQL: "^\\x0a\\x00\\x00\\x00\\x00\\x00"
  SIP-UDP: "^INVITE|ACK|BYE|CANCEL|OPTIONS|REGISTER"
  NTP: "^\\x1b\\x00\\x00\\x00"
  VNC: "^RFB\\s+"
