package main

// Default configuration values
var defaultConfig = Config{
	Interface:      "en0",
	SnapshotLength: 1600,
	PromiscMode:    true,
	Timeout:        "0s", // BlockForever
	Filter:         "tcp",
	Verbose:        false,
	ProtocolPatterns: map[string]string{
		"HTTP":       `^(?:GET|POST|HEAD|PUT|DELETE|OPTIONS|CONNECT|TRACE)\s`,
		"TLS":        `^\x16\x03[\x00-\x03]`,
		"SSH":        `^SSH-\d\.\d`,
		"SMTP":       `^(?:220|250|354|450|500)`,
		"FTP":        `^(?:220|230|331|530)`,
		"DNS":        `^.{2}[\x01\x02].{2}`,
		"BitTorrent": `^(\x13|d1:)BitTorrent protocol`,
	},
	ColorScheme: map[string]string{
		"Authentication":     "red,bold",
		"API Key":            "red,bold",
		"Credit Card":        "red,bold",
		"Private Key":        "red,bold",
		"JWT":                "red,bold",
		"Email":              "yellow,bold",
		"Sensitive Protocol": "magenta,bold",
		"Known Application":  "blue,bold",
		"TLS SNI":            "cyan,bold",
		"Interesting Path":   "green,bold",
		"Default":            "gray,bold",
	},
	WellKnownPorts: map[uint16]string{
		80:    "HTTP",
		443:   "HTTPS",
		21:    "FTP",
		22:    "SSH",
		23:    "Telnet",
		25:    "SMTP",
		53:    "DNS",
		110:   "POP3",
		143:   "IMAP",
		3306:  "MySQL",
		5432:  "PostgreSQL",
		6379:  "Redis",
		27017: "MongoDB",
	},
	Applications: map[string][]string{
		"Netflix":   {"netflix.com", "nflx.net"},
		"YouTube":   {"youtube.com", "googlevideo.com", "ytimg.com"},
		"Facebook":  {"facebook.com", "fbcdn.net", "facebook.net"},
		"Instagram": {"instagram.com", "cdninstagram.com"},
		"Twitter":   {"twitter.com", "twimg.com"},
	},
	Paths: map[string]string{
		"Admin Panel": `admin|login|dashboard|panel|wp-admin|wp-login|wp-content|wp-includes|wp-json|wp-`,
		"API":         `api|rest|graphql|json|xml|rpc|soap`,
		"Config":      `config|settings|conf|cfg|env|ini|properties|yml|yaml|toml|json`,
		"Backup":      `backup|old|archive|bak|bck|bkp|tmp|temp|swp|save|copy|dump|download|export|import`,
		"Log":         `log|logs|access|error|debug|info|warn|warning|trace|audit|event|history|activity`,
		"Database":    `db|database|sql|mysql|sqlite|postgres|mongodb|redis|dbase|dbadmin|db-backup|db-dump|db-export|db-import|db-restore|db-sql|db-test|db-update|db-upgrade|db-backup|db-restore|db-migrate|db-rollback|db-recover|db-repair|db-configure|db-connect|db-disconnect`,
		"Secret":      `secret|key|token|password|passwd|pass|pwd|auth|credential|api-key|api-key|access-key|access-key|private-key|private-key|public-key|public-key|jwt|bearer|session|cookie|csrf|nonce|signature|hash|salt|iv|aes|des|rsa|dsa|ecdsa|ed25519|md5|sha1|sha256|sha512|bcrypt|scrypt|argon2`,
	},
}
